### ISSUE TITLE
Collabse procedure and functions

### ISSUE THREAD

**Issue by rugk** [alefragnani/atom-language-pascal#10]
It would be good if you could collapse whole functions and procedures.

**Comment by alefragnani** [comment]
That's something that I also wanted, but never looked how to change it. 

I see `foldingStartMarker` and `foldingStopMarker` in grammar definition, but doesn't appear to be used. For instance, C# has `#region / #endregion` defined, but the folding doesn't work.

I will take a look and see if it is something supported in Atom (since the grammars are converted from TextMate). I will let you know.

**Comment by alefragnani** [comment]
It seems that folding is based on _identation_, not in _grammar definition_. Look at this [issue](https://github.com/atom/first-mate/issues/48).

I will keep an eye on that issue and when it is released, I will update the language to support it as well.

**Comment by alefragnani** [comment]
I'm closing this issue since nothing has changed in Atom side in more than an year. Neither a milestone has been defined yet.
I'm subscribing that issue so if something changes, I'll be notified and could reopen this.
