### ISSUE TITLE
Buggy Auto Indentation

### ISSUE THREAD

**Issue by tsztoyip** [alefragnani/atom-language-pascal#19]
Been working on a pascal project recently so I discovered a few weird behaviours of the indentation rules:
Instead of these:
```
var
    i:integer;
begin
...
```
or
```
if true then
    writeln('Hello World!');
writeln('Bye World?');
...
```
The auto indentation function changes those to:
```
var
    i:integer;
    begin
...
```
or
```
if true then
    writeln('Hello World!');
    writeln('Bye World?');
...
```
I'm not sure if this is a bug due to this language or it's atom's fault but it's quite frustrating 'cause auto indentation is basically unusable. I tried solving it by changing the cson files but I'm not experienced with packages of atom so I just left it there. Fixing this would be great 😄

**Comment by alefragnani** [comment]
Hi @tsztoyip ,

It is working _as designed/supported_, but to be able to work as your request, it would be a combination of Atom and Package enhancements.

The indentation is defined in `language-pascal.cson` file, and it handles all lines below. There is another key for _only next line_ indentation rule called `indentNextLinePattern`, but it is not supported by Atom https://discuss.atom.io/t/add-support-for-indentnextlinepattern-as-in-textmate-for-more-advanced-indentation/14199/3.

So, unless Atom supports this TextMate rule, these config will not work.

Hope this helps

**Comment by tsztoyip** [comment]
@alefragnani  Okay, thanks for the quick reply, hope atom will include `indentNextLinePattern` in the near future 😄

**Comment by santimonti** [comment]
No news about how to fix it yet?

**Comment by alefragnani** [comment]
Hi @santimonti ,

I’m not sure, but looking at the thread commented above, it seems the problem remains with no solution from the Atom’s team. Just recently they moved to another syntax engine (tree-sitter) but I didn’t dig that much to see how powerful it is. It requires recreating the package from the ground up, but I’m not that interested, because I’ve moved most of my development to VS Code for quite a while.

I found [this solution](https://github.com/atom/language-java/pull/82) from the Java language package. Maybe it would also work here. You could try out to see if it works for you, and if yes, send a PR. I’ll be glad to merge and release an update.

Hope this helps
