### ISSUE TITLE
Tab Length

### ISSUE THREAD

**Issue by fedorpashin** [alefragnani/atom-language-pascal#20]
Hello! I noticed that the default tab length in the package settings is 4, but actually it is 2. I can't change it to 4. It happens only if the default tab length in editor settings is 4.

**Comment by alefragnani** [comment]
Hi @fedorpashin ,

It appears to be an _UI_ Atom issue, because if you use other value than the _default editor value_, it works. When you type the _same value_, it is cleared, but if you type any other value, it remains there.

I could make it work if I changed `config.cson` file directly, instead of using the UI (File / Setting). Add this lines to your `config.cson` file:

```
".pascal.source":
  editor:
    tabLength: 4
```
Now, if I hit TAB on any pascal file, it will jump 4 characters, as expected.

Hope this helps

ps: Please, report this UI issue in atom repository...

**Comment by fedorpashin** [comment]
1
