### ISSUE TITLE
Problem with tabulations

### ISSUE THREAD

**Issue by touatily** [alefragnani/atom-language-pascal#23]
Even if we change the number of spaces for tabulations in settings, atom uses two (2) spaces for tabulations for .pas files.

**Comment by vv7v7** [comment]
Dear @touatily, Are you sure that atom adds 2 spaces only in .pas files ?

**Comment by touatily** [comment]
Yes, I checked.
Even if I change the tabulations in atom's settings. All files other than ".pas" takes in count the new tabulations (number of space). However, files ".pas" still use 2-spaces tabulations.

**Comment by alefragnani** [comment]
Hi @touatily ,

That's weird, because I remember this working fine for a long time. Maybe something has changed in Atom internals and is now causing this behavior. I could reproduce the problem, and it seems related to the presense of tab definitions in the language `settings\language-pascal.cson` which was added 2 years ago by #9 .

I will try to determine if this is an issue with my package, or in Atom itself like #20 was. Maybe not an UI issue but something related to language loading itself.

@vv7v7 , thanks for helping 👍

**Comment by alefragnani** [comment]
Hi @touatily @vv7v7  ,

I did some tests, looked at Atom's forum and it seems this is how Atom works. 

If the package has a `tabLenght` defined, it will be used _even if you define Atom with another value_. And just like #20, the issue in Atom UI prevents you from forcing the `tabLength` to Pascal with the same value as the core.

The solution, is to add this in your `config.cson` file, forcing the new value. Like this:

```cson
'.source.pascal':
      editor:
            tabLength: 6
```
Hope this helps...

If you are curious, these are some references found in Atom's forum:

* https://discuss.atom.io/t/why-is-tab-spacing-different-between-languages/42021
* https://discuss.atom.io/t/tab-length-setting-is-not-saved-for-language-packages/14255/2
