### ISSUE TITLE
Wrong highlight when use procedure forward

### ISSUE THREAD

**Issue by viniciusfbb** [alefragnani/atom-language-pascal#36]
When declare:
```delphi
procedure A(const S: string); forward;
```
text within parameters is not highlighted. The interesting thing is that if the method is a function, it works normally:
```delphi
function A(const S: string): Boolean; forward;
```

See the print:
![image](https://user-images.githubusercontent.com/11139086/147119011-2edc4010-83bd-4e6e-84b7-d9d80ca73ff2.png)

**Comment by viniciusfbb** [comment]
The funny thing is that github code syntax also has the same problem. 😂😂

**Comment by alefragnani** [comment]
Hi @viniciusfbb ,

Yep, really funny. It seems an error in the original TextMate grammar, which this Atom package was based on, because my VS Code extension has the same issue. GitHub probably uses the same engine.

Another funny scenario. Add an empty space between the function name and the open parenthesis, and it will work

```pascal
procedure A (const S: string); forward;
```

The problem must be here, if you would like to give it a try
```
{
    'captures':
      '1':
        'name': 'storage.type.prototype.pascal'
      '2':
        'name': 'entity.name.function.prototype.pascal'
    'match': '\\b(?i:(function|procedure|constructor|destructor))\\b\\s+(\\w+(\\.\\w+)?)(\\(.*?\\))?;\\s*(?=(?i:attribute|forward|external))'
    'name': 'meta.function.prototype.pascal'
  }
```
